version: "3.7"
services:
    brython:
        build:
            context: .
        volumes:
            - ./web/:/opt/web/
    web:
        image: nginx:1.15.3
        links:
            - brython
        ports:
            - "8001:80"
        volumes:
            - ./web/:/usr/share/nginx/html/

